apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:meS1ahZSCW4feaI9iwXMW8O6WqTjTvZL0Ci1DCMqi5fpohu6X4stfYTmjTV1Or0DdTM1jDaDJ2FNkvYx4BQVlcZDnYS3PxlqnKf+Og0Jv+FCw2RR0bB839XomOGGUYc+T287DgDJiAUpFzwPaxWlR7n8yKOyO1cuHAqmT+zglWXTI57N88r18uXxq+gfKmOWgnZjEDJdsegrF0no+xsp6gw48o1d+LgPdmFO9gG+dFFzai0eA5S9WWR0iU3wrT9YK8vWeBowSLd37hBYoq8X7FmrHvk8IJO0vdHiGiDbIt9ZDnSwBbLZL9LgyQk=,iv:X78kCWl7/1tT0AroN+svbRuWXrKD6BXZxzG+2a6/mD0=,tag:Trq1nDIWFo9Hza1x1/En/A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age1knvscpcgrfenesnpp3uf9wlvpcn0q4nd77fdssnwae20f4qt64fs8q4q68
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIamEyeDI5ZUczV0lVMHc0
            QThsZVRsZWxXMXpZWVg2UlNFWFRZaERNWlhFCmp6anJzM3NMdW9nbTRJQ0RJUVZH
            Z205dDdrUk1XdUh5bm1rdzhWaVRhYzAKLS0tIHlWUHRTdlR4UlB0L2NEZVY2WGRN
            S2trUWc1MDltRmRxNGNMM0crT202SWsKUn1YAujK8R0jwk1HinqBKQFah6JmHsn7
            OKSGGkl97Z3o1Hh5fYUG0wCeqIUITf7mrJQLiCwCidE0dIi4/lQDLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T22:46:51Z"
    mac: ENC[AES256_GCM,data:wvsTGDYp3Peykq4snKktqgC4V+GFTUbjOxfc38XX1iPouXP7E7uppymc3KQQT5ICCs+A9aHwV2Wl3y3nI56AOGZ5E0R5O8evakVL4sxBXrY1Zdf1ywWm92/iFMguryApAkf/9XmDGXgiq3WAAxONXlPv9WPePlUSwUCQv1fHzKA=,iv:H7bpXzrH9HdcC1E8DMXimmKTYpZnJtLKAMBMp2ej7o0=,tag:NxBHUJ1Hy+rWFVAEziA17g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
