apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:8KLRW59xDM4=,iv:S39UfJ4qst+tGV2QPXoxxHAQqEvRGdwqLMXEPsQXIUc=,tag:LISkGXuHn0DhxUAgAA+ulg==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:7u5/jXi06xQx4pTdwvTl4A==,iv:tmXVxn+s6eauHkpYEPyAh+khMB2iXH9zEljPBuALQDU=,tag:WgJQUWfZwInEvfqFXmCeSQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-container-env
sops:
    age:
        - recipient: age1knvscpcgrfenesnpp3uf9wlvpcn0q4nd77fdssnwae20f4qt64fs8q4q68
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUmdKR3BSQ0EzaWZSVWZB
            blFjMGpOVWRpa0VaRy91MXQ0OWpWQUhXaEVNCk5xdFJoRkRSdEFQWDVuZjBFWnpN
            c3RsZmwxa2lQZkpiV0tPazZ0TXA2MlkKLS0tIFRVdWNuT1FrWXE3ak5ldGxNWnBa
            SlVjRUJEdzZCYncvcXZzMzBaaEk0dU0K9pRn1lmCpPZDVOHNDWoDgnpV74vcQ5HM
            LOhhoHa3ig4ZAFzjIfIri8unMlAdnoAuw3mVLxc5F7KjHXHCV1NLUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T22:58:01Z"
    mac: ENC[AES256_GCM,data:wZWy7Xws25iUKUW+ck4xJJhSjfbyJJj93tpT1O7kiKHV7mFl99Lq4z+0TtamC+wRT301ZEsb1ONqB2Onh9PUpt4vqlF9IZsfqu0YhiQd1iGoHlT/PjCpwHrST9NcsGNEUjLqhbi7+5gtLbOAbQ5HuBTS9NC16CHVgFKGqZvlZx0=,iv:1NXVM5awGxGffgguh1MxYaCp1TbBMDQTcLNsXtaGZJ0=,tag:33p3Sh0RwmJz/6P2PN5Wew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
